(header "ctype.h")

(import "locale.h" locale_t)

(func int isalnum (int))
(func int isalnum_l (int locale_t))
(func int isalpha (int))
(func int isalpha_l (int locale_t))
(func int isblank (int))
(func int isblank_l (int locale_t))
(func int iscntrl (int))
(func int iscntrl_l (int locale_t))
(func int isdigit (int))
(func int isdigit_l (int locale_t))
(func int isgraph (int))
(func int isgraph_l (int locale_t))
(func int islower (int))
(func int islower_l (int locale_t))
(func int isprint (int))
(func int isprint_l (int))
(func int ispunct (int))
(func int ispunct_l (int locale_t))
(func int isspace (int))
(func int isspace_l (int locale_t))
(func int isupper (int))
(func int isupper_l (int locale_t))
(func int isxdigit (int))
(func int isxdigit_l (int locale_t))
(func int tolower (int))
(func int tolower_l (int locale_t))
(func int toupper (int))
(func int toupper_l (int locale_t))


