(header "stdlib.h")

(import "stddef.h" NULL size_t wchar_t)
(import "sys/wait.h" 
        WEXITSTATUS WIFEXITED WIFSIGNALED WIFSTOPPED
        WNOHANG WSTOPSIG WTERMSIG WUNTRACED)

(macroval* EXIT_FAILURE EXIT_SUCCESS RAND_MAX MB_CUR_MAX)

(struct div_t
        (quot int)
        (rem int))

(struct ldiv_t
        (quot long)
        (rem long))

(struct lldiv_t
        (quot long long)
        (rem long long))


(func void _Exit (int))
(func long a64l ((* char const)))
(func void abort ())
(func int abs (int))
(func int atexit ((func void ())))
(func double atof ((* char const)))
(func int atoi ((* char const)))
(func (long long) atoll ((* char const)))
(func (* void) bsearch 
      ((* void const) (* void const) size_t size_t 
                      (func int ((* void const) (* void const)))))
(func (* void) calloc (size_t size_t))
(func div_t div (int int))
(func double drand48 ())
(func double erand48 (* short unsigned))
(func void exit (int))
(func void free ((* void)))
(func (* char) getenv ((* char const)))
(func int getsubopt ((** char) (** char const) (** char)))
(func int grantpt (int))
(func (* char) initstate (unsigned (* char) size_t))
(func long jrand48 (* short unsigned))
(func (* char) l64a (long))
(func long labs (long))
(func void lcong48 ((* short unsigned)))
(func ldiv_t ldiv (long long))
(func (long long) llabs (long long))
(func lldiv_t lldiv ((long long) (long long)))
(func long lrand48 ())
(func (* void) malloc (size_t))
(func int mblen ((* char const) size_t))
(func size_t mbtowcs ((* wchar_t restrict) (* char const restrict) size_t))
(func int mbtowc ((* wchar_t restrict) (* char const restrict) size_t))
(func (* char) mkdtemp ((* char)))
(func int mkstemp ((* char)))
(func long mrand48 ())
(func long nrand48 ((* short unsigned)))
(func int posix_memalign ((** void) size_t size_t))
(func int posix_openpt (int))
(func (* char) ptsname (int))
(func void qsort ((* void) size_t size_t 
                           (func int ((* void const) (* void const)))))
(func int rand ())
(func int rand_r ((* unsigned)))
(func long random ())
(func (* void) realloc ((* void) size_t))
(func (* char) realpath ((* char const restrict) (* char restrict)))
(func (* short unsigned) seed48 ((* short unsigned)))
(func int setenv ((* char const) (* char const) int))
(func void setkey ((* char const)))
(func (* char) setstate ((* char)))
(func void srand (unsigned))
(func void srand48 (long))
(func void srandom (unsigned))
(func double strtod ((* char const restrict) (** char restrict)))
(func float strtof ((* char const restrict) (** char restrict)))
(func long strtol ((* char const restrict) (** char restrict) int))
(func (long double) strtold ((* char const restrict) (** char restrict)))
(func (long long) strtoll ((* const char restrict) (** char restrict) int))
(func (unsigned long) strtoul ((* char const restrict) (** char restrict) int))
(func (unsigned long long) strtoull ((* char const restrict) (** char restrict)
                                                             int))
(func int system ((* char const)))
(func int unlockpt (int))
(func int unsetenv ((* char const)))
(func size_t wcstombs ((* char restrict) (* wchar_t const) size_t))
(func int wctomb ((* char) wchar_t))

